# Generated by Django 2.1 on 2018-09-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.URLField(max_length=500),
        ),
    ]
